### PR TITLE
fix: multiple compilations crash

### PR DESCRIPTION
**Pull request by JeremiGendron**
The idea is very simple: allow up to 10 jobs to be in the 'queue' at once; when an 11th job is scheduled to be created, then `this.jobs[0].kill()` where every job is a `solcWorker`.

I haven't tested this, I suggest you verify and mess with the 10 max value to see if there's a sweetspot.

#198

### CODE REVIEW

**Comment by JeremiGendron** [comment]
Implemented job tracking so there's no double fire even if atom is buggy and put that on top of killing older jobs when new ones come in. I'll set up a proper environment so I can run good tests because it would be better to have more granular control (allow 1 job per file, instead of global limit).

**Comment by JeremiGendron** [comment]
@0mkara Now, only one job is allowed per filename. This fixed the crash issue (holding CTRL+S doesn't stop the computer). Unfortunately, the "Compiled" and "Compiling..." button is now buggy and though multiple contracts compile at once, only the last compiled one has the ability to have its name shown in the UI ("a.sol" in green when compilation finished). NOTE: compilation errors can be seen even though multiple files are being compiled.

**Comment by JeremiGendron** [comment]
Figured out how to develop for the package, very interesting workflow!

**Comment by 0mkara** [comment]
This looks cool so far. The UI can be buggy because previous workflow changed. I will look into the PR and let you know my views on the PR & UI changes.

**Comment by 0mkara** [comment]
screenshot from 2018-11-20 10-54-14
I tried to compile `greeter.sol` multiple times. Where I could create 15 processes for atom (by default it has 3/4 process running).

I think we can add a simple check with sha that checks if the content of the file changed or not. If it changed we can kill the old process and create a new one, but if nothing has really changed and there is already a compilation job running for the file we do not need to submit it for compilation.

**Comment by JeremiGendron** [comment]
ok let me modify that

**Comment by 0mkara** [comment]
Have two contracts
`greeter.sol`
```solidity
pragma solidity ^0.5.0;
import "./mortal.sol";

contract Greeter is Mortal {
    /* Define variable greeting of the type string */
    string greeting;

    /* This runs when the contract is executed */
    constructor(string memory _greeting) public {
        greeting = _greeting;
    }

    /* Main function */
    function greet() public view returns (string memory) {
        return greeting;
    }
}
```
`mortal.sol`
```solidity
pragma solidity ^0.5.0;

contract Mortal {
    /* Define variable owner of the type address */
    address payable owner;

    /* This function is executed at initialization and sets the owner of the contract */
    function mortal() public { owner = msg.sender; }

    /* Function to recover the funds on the contract */
    function kill() public { if (msg.sender == owner) selfdestruct(owner); }
}
```
If you try to compile them multiple times it works for the first time. It does not work after they are compiled for the first time.
screenshot from 2018-11-20 14-15-42

I think with slight modification to the current approach we should be able to achieve perfection.

**Comment by JeremiGendron** [comment]
It should compile them if you change the contents of the file. It will
simply never compile if the last compilation for that file is the same as
what you're trying to compile.

**Comment by 0mkara** [comment]
Yes, and that behavior is wrong. I think we should clear the stack once compilation worker exists. We handle that between [L60](https://github.com/0mkara/etheratom/blob/110f5fa14b7645db6d40faac27687ca96d407653/lib/web3/methods.js#L60) - [L71](https://github.com/0mkara/etheratom/blob/110f5fa14b7645db6d40faac27687ca96d407653/lib/web3/methods.js#L71).

**Comment by 0mkara** [comment]
screenshot from 2018-11-21 09-58-24

We could track the workers by hash id and clear the job stack as they finishes. Currently we are having loosely attached workers.

```js
solcWorker.on('message', m => {
                if(m.compiled) {
                    const compiled = JSON.parse(m.compiled); // pass back hash id from worker
                    // clear job stack here
                    this.store.dispatch({ type: SET_COMPILED, payload: compiled });
                    this.store.dispatch({ type: SET_COMPILING, payload: false });
                }
});
```

**Comment by JeremiGendron** [comment]
@0mkara will review in the morning.

**Comment by 0mkara** [comment]
5f67f92 is definitely what we needed. Thank you very much @JeremiGendron :heart: :heart_eyes:

**Comment by JeremiGendron** [comment]
@0mkara glad you like it!

**Pull request merged**
