### PR TITLE
Makes UI width more responsive

### PR DESCRIPTION
**Pull request by ddcech**
this just changes the layout to shrink a bit more.

### CODE REVIEW

**Comment by 0mkara** [comment]
Thank you @ddcech for your contribution. These updates will be merged with next release.

**Comment by 0mkara** [comment]
Hello @ddcech,
I am facing some unexpected problem after merging your commits.
screenshot from 2017-06-28 13-27-16
This is how atom statusbar git status looks before I install etheratom merged your commits.
screenshot from 2017-06-28 13-27-54
This is how atom statusbar git status looks  after I install etheratom merged your commits.
Can you please check this issue and try to update your changes with possible fix ?

**Comment by ddcech** [comment]
My apologies. It should be fixed now.
This is my first time working with an Atom plugin and I didn't realize that the css class could overwrite a global Atom class. I fixed it by nesting all etheratom css classes under the .etheratom class name.
If you see any other issues just let me know :)

**Comment by 0mkara** [comment]
Lost scrolling capability of Etheratom panel

screenshot from 2017-06-30 12-37-53

With your style panel area is not scrollable. Can you please check that ?

**Pull request merged**
